version: "3"

services:
  scraper:
    build: scraper
    ports:
      - "8080:8080"
    volumes:
      - "./scraper/app:/go/src/app"
    # command: go run main.go
    tty: true
  botter:
    build: botter
    ports:
      - "8081:8081"
    volumes:
      - "./botter:/app"
    tty: true
